ignore:
  - "compiler-plugin/src/main/java/io/ballerina/stdlib/persist/sql/compiler/exception/NotSupportedExpressionException.java"
  - "native/src/main/java/io/ballerina/stdlib/persist/sql/Constants.java"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
