[plugin]
id = "persist.sql-compiler-plugin"
class = "io.ballerina.stdlib.persist.sql.compiler.PersistSqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/persist.sql-compiler-plugin-@project.version@.jar"

[[dependency]]
path = "./lib/persist-native-@persist.native.version@.jar"
