[plugin]
id = "persist.sql-compiler-plugin"
class = "io.ballerina.stdlib.persist.sql.compiler.PersistSqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/persist.sql-compiler-plugin-1.5.0-SNAPSHOT.jar"

[[dependency]]
path = "./lib/persist-native-1.5.0-20241122-123800-2ae4d59.jar"

[[dependency]]
path = "./lib/persist-compiler-plugin-1.5.0-20241122-123800-2ae4d59.jar"
