[plugin]
id = "persist.sql-compiler-plugin"
class = "io.ballerina.stdlib.persist.sql.compiler.PersistSqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/persist.sql-compiler-plugin-1.4.0-SNAPSHOT.jar"

[[dependency]]
path = "./lib/persist-native-1.4.0-20240808-102300-3b855e5.jar"

[[dependency]]
path = "./lib/persist-compiler-plugin-1.4.0-20240808-102300-3b855e5.jar"
