[plugin]
id = "persist.sql-compiler-plugin"
class = "io.ballerina.stdlib.persist.sql.compiler.PersistSqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/persist.sql-compiler-plugin-1.4.2-SNAPSHOT.jar"

[[dependency]]
path = "./lib/persist-native-1.4.1-20241113-122000-306cc63.jar"

[[dependency]]
path = "./lib/persist-compiler-plugin-1.4.1-20241113-122000-306cc63.jar"
