[plugin]
id = "persist.sql-compiler-plugin"
class = "io.ballerina.stdlib.persist.sql.compiler.PersistSqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/persist.sql-compiler-plugin-1.2.2-SNAPSHOT.jar"

[[dependency]]
path = "./lib/persist-native-1.2.1-20231130-100000-cca5690.jar"
