[plugin]
id = "persist.sql-compiler-plugin"
class = "io.ballerina.stdlib.persist.sql.compiler.PersistSqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/persist.sql-compiler-plugin-1.2.0-SNAPSHOT.jar"

[[dependency]]
path = "./lib/persist-native-1.2.0-20230911-142300-ddef67b.jar"
